stages: [test]

fairness-ci:
  image: python:3.12-slim
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - pip install -e .[dev] -r requirements.txt
  script:
    # 1) Lint
    - black --check fairness_pipeline_dev_toolkit tests
    - flake8 fairness_pipeline_dev_toolkit

    # 2) Unit tests + coverage
    - pytest --cov=fairness_pipeline_dev_toolkit --cov-report=term-missing -q

    # 3) Prepare tiny synthetic CSV (no repo data dependency)
    - python - <<'PY'
      import pandas as pd, numpy as np
      rng = np.random.default_rng(0)
      n = 500
      df = pd.DataFrame({
          "y_true": rng.integers(0, 2, n),
          "y_pred": rng.integers(0, 2, n),
          "group": rng.choice(["A","B"], size=n, p=[0.55, 0.45])
      })
      df.to_csv("ci_sample.csv", index=False)
      PY

    # 4) Fairness smoke gate
    - python scripts/quick_fairness_check.py \
        --csv ci_sample.csv \
        --y-true y_true --y-pred y_pred \
        --sensitive group \
        --threshold 0.12 \
        --min-group-size 20

    # 5) Markdown report (CLI)
    - python -m fairness_pipeline_dev_toolkit.cli.main validate \
        --csv ci_sample.csv \
        --y-true y_true --y-pred y_pred \
        --sensitive group \
        --min-group-size 20 \
        --out fairness_report.md
  artifacts:
    when: always
    paths:
      - fairness_report.md
    expire_in: 7 days
